--- #YAML:1.0
name:                Tie-TZ
version:             4
abstract:            Tied TZ env var calling tzset() when changed.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
optional_features:
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Test::Pod: 1.00
no_index:
    directory:
        - devel
        - junk
        - t
resources:
    homepage: http://www.geocities.com/user42_kevin/tie-tz/index.html
    license: http://www.gnu.org/licenses/#GPL
